import type { WidgetDefinition } from "@nexus/schemas";
import { audioValue, refreshProperty } from "../helpers.js";

/** Progress towards a target, from a live source or a figure the user keeps updated. */
export const goalProgressWidget: WidgetDefinition = {
  type: "commerce.goalProgress",
  name: "Goal progress",
  summary: "How far along you are towards a target you set.",
  category: "Commerce",
  icon: "target",
  defaultSpan: { columns: 4, rows: 2 },
  minimumSpan: { columns: 2, rows: 1 },
  dataEndpoint: "/api/widgets/goal-progress",
  defaultRefreshSeconds: 600,
  helpTopicId: "widget-goal-progress",
  previewHint: "Track it by hand, or point it at a connected figure.",
  schema: {
    label: {
      kind: "text",
      label: "Goal",
      help: "What you are working towards, in your own words.",
      defaultValue: "Monthly goal",
      maxLength: 60,
      group: "Content",
    },
    target: {
      kind: "number",
      label: "Target",
      help: "The number that counts as finished.",
      defaultValue: 100,
      min: 0,
      max: 1000000000,
      step: 1,
      group: "Content",
    },
    unit: {
      kind: "text",
      label: "Unit",
      help: "Shown after the numbers, for example “orders” or “£”.",
      defaultValue: "",
      maxLength: 16,
      group: "Appearance",
    },
    valueSource: {
      kind: "select",
      label: "Where the current figure comes from",
      help: "Keep it yourself, or read it from a connected service.",
      defaultValue: "manual",
      options: [
        { value: "manual", label: "I will update it myself" },
        { value: "shopifySales", label: "Shopify sales" },
        { value: "wooRevenue", label: "WooCommerce revenue" },
        { value: "workflowRuns", label: "Successful workflow runs" },
      ],
      group: "Data",
    },
    manualValue: {
      kind: "number",
      label: "Current figure",
      help: "The number so far. Change it whenever you like — every change is undoable.",
      defaultValue: 0,
      min: 0,
      max: 1000000000,
      step: 1,
      group: "Data",
      visibleWhen: { property: "valueSource", equals: "manual" },
    },
    deadline: {
      kind: "text",
      label: "Deadline",
      help: "Optional date in YYYY-MM-DD form. Adds “4 days left” under the bar.",
      defaultValue: "",
      maxLength: 10,
      group: "Content",
    },
    display: {
      kind: "select",
      label: "Show as",
      help: "How progress is drawn.",
      defaultValue: "bar",
      options: [
        { value: "bar", label: "A bar" },
        { value: "ring", label: "A ring" },
        { value: "figures", label: "Figures only" },
      ],
      group: "Appearance",
    },
    celebrate: {
      kind: "toggle",
      label: "Celebrate when it is reached",
      help: "A short animation and sound the first time the goal is met. Respects reduced motion and quiet hours.",
      defaultValue: true,
      group: "Behaviour",
    },
    celebrationSound: {
      kind: "audio",
      label: "Celebration sound",
      help: "Played once when the goal is reached.",
      defaultValue: audioValue({ builtInId: "nexus-fanfare", volume: 0.5 }),
      group: "Behaviour",
      visibleWhen: { property: "celebrate", equals: true },
    },
    refreshSeconds: refreshProperty(600),
  },
};
