#!/bin/bash
# Generated by scripts/generate-assets.mjs — macOS only.
# iconutil ships with the Apple Command Line Tools; there is no Linux equivalent,
# so this step runs on the user's Mac (PACKAGE_NEXUS.command calls it for you).
set -euo pipefail
cd "$(dirname "$0")"
iconutil --convert icns --output NexusOS.icns NexusOS.iconset
echo "Created $(pwd)/NexusOS.icns"
