import type { WidgetDefinition } from "@nexus/schemas";
import { refreshProperty, titleProperty } from "../helpers.js";

/** Runs one saved prompt against a connected provider and shows the reply in place. */
export const promptRunnerWidget: WidgetDefinition = {
  type: "ai.promptRunner",
  name: "Prompt runner",
  summary: "Run one prepared prompt and read the reply without leaving the page.",
  category: "AI",
  icon: "wand.and.stars",
  defaultSpan: { columns: 6, rows: 4 },
  minimumSpan: { columns: 3, rows: 2 },
  requiresConnection: "ai-provider",
  dataEndpoint: "/api/widgets/ai/run",
  defaultRefreshSeconds: 0,
  helpTopicId: "widget-prompt-runner",
  previewHint: "Needs an AI provider connected. Replies are shown as model output, never as instructions Nexus OS follows.",
  schema: {
    title: titleProperty("Prompt runner"),
    provider: {
      kind: "connection",
      label: "Provider",
      help: "Which connected AI service answers this prompt. Keys are stored in the Keychain and never in your layout.",
      defaultValue: null,
      service: "ai-provider",
      group: "Data",
    },
    model: {
      kind: "select",
      label: "Model",
      help: "Larger models reason better; smaller models answer faster and cost less.",
      defaultValue: "balanced",
      options: [
        { value: "fast", label: "Fast", help: "Short answers, lowest cost." },
        { value: "balanced", label: "Balanced", help: "The usual choice." },
        { value: "deep", label: "Most capable", help: "Slower, best for hard problems." },
      ],
      group: "Data",
    },
    prompt: {
      kind: "longText",
      label: "Prompt",
      help: "What to ask. Use {{selection}} to include whatever you have selected, and {{clipboard}} for the clipboard.",
      defaultValue: "",
      placeholder: "Summarise this in five bullet points: {{clipboard}}",
      maxLength: 8000,
      group: "Content",
    },
    systemPrompt: {
      kind: "longText",
      label: "Standing instructions",
      help: "Sent before every run to set the tone, for example “British English, no preamble”.",
      defaultValue: "",
      maxLength: 4000,
      group: "Advanced",
      advanced: true,
    },
    temperature: {
      kind: "slider",
      label: "Creativity",
      help: "Lower is more predictable and repeatable; higher varies more between runs.",
      defaultValue: 0.3,
      min: 0,
      max: 1,
      step: 0.05,
      group: "Advanced",
      advanced: true,
    },
    maxOutputTokens: {
      kind: "number",
      label: "Longest reply",
      help: "An upper limit on the reply length, measured in tokens. Roughly four characters to a token.",
      defaultValue: 1024,
      min: 64,
      max: 32000,
      step: 64,
      unit: "tokens",
      group: "Advanced",
      advanced: true,
    },
    runShortcut: {
      kind: "shortcut",
      label: "Run shortcut",
      help: "Press this to run the prompt without clicking.",
      defaultValue: "",
      group: "Behaviour",
      advanced: true,
    },
    showUsage: {
      kind: "toggle",
      label: "Show what each run used",
      help: "Displays tokens used and the estimated cost after every run, so nothing is a surprise on your bill.",
      defaultValue: true,
      group: "Appearance",
    },
    refreshSeconds: refreshProperty(3600),
  },
};
